# Laurel converts Linux Audit events into one JSON object per line.
directory = "/var/log/spe-audit"
user = "_laurel"
statusreport-period = 0
input = "stdin"

[auditlog]
file = "os.jsonl"
size = 10000000
generations = 5

[transform]
execve-argv = ["array"]

[translate]
userdb = true
universal = true
